<?php
// module/Album/view/album/album/index.phtml:

$title = 'List of Restaurants';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
<tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Rank</th>
</tr>
<?php foreach ($restaurants as $restaurant) : ?>
<tr>
    <td><?php echo $this->escapeHtml($restaurant->name);?></td>
    <td><?php echo $this->escapeHtml($restaurant->address);?></td>
    <td><?php echo $this->escapeHtml($restaurant->phone);?></td>
    <td><?php echo $this->escapeHtml($restaurant->rank);?></td>
    
</tr>
<?php endforeach; ?>
</table>