<script type="text/javascript">
$.fn.studyplay_star=function(options,callback){
	//默认设置
	var settings ={
		MaxStar      :20,
		StarWidth    :23,
		CurrentStar  :5,
		Enabled      :true,
		Half         :0
		};	
	if(options) { jQuery.extend(settings, options); };
	var container = jQuery(this);
	container.css({"position":"relative"})
	.html('<ul class="studyplay_starBg"></ul>')	
	.find('.studyplay_starBg').width(settings.MaxStar*settings.StarWidth)
	.html('<li class="studyplay_starovering" style="width:'+settings.CurrentStar*settings.StarWidth+'px; z-index:0;" id="studyplay_current"></li>');
	if(settings.Enabled)
	{
	var ListArray = "";	
	if(settings.Half==0)
	{
	for(k=1;k<settings.MaxStar+1;k++)
	{	
		ListArray +='<li class="studyplay_starON" style="width:'+settings.StarWidth*k+'px;z-index:'+(settings.MaxStar-k+1)+';"></li>';
	}
	}
	
	if(settings.Half==1)
	{
	for(k=1;k<settings.MaxStar*2+1;k++)
	{	
		ListArray +='<li class="studyplay_starON" style="width:'+settings.StarWidth*k/2+'px;z-index:'+(settings.MaxStar-k+1)+';"></li>';
	}
	}
	
	container.find('.studyplay_starBg').append(ListArray)
	container.find('.studyplay_starON').hover(function(){											  
	$(this).removeClass('studyplay_starON').addClass("studyplay_starovering");
	$("#studyplay_current").hide();
	},
	function(){
	$(this).removeClass('studyplay_starovering').addClass("studyplay_starON");
	$("#studyplay_current").show();
	})
	.click(function(){
        var studyplay_count = settings.MaxStar - $(this).css("z-index")+1;
        if(settings.Half==0)
        $("#studyplay_current").width(studyplay_count*settings.StarWidth)
        if(settings.Half==1)
        $("#studyplay_current").width(studyplay_count*settings.StarWidth/2)
        //回调函数
        if (typeof callback == 'function') {
        if(settings.Half==0)
        callback(studyplay_count);
        if(settings.Half==1)
        callback(studyplay_count/2);
        return ;
        }
        })
 }	
}	
</script>

<?php
// module/Album/view/album/album/index.phtml:

$title = 'List of Restaurants';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>list mode</h3>
<h3>photo mode</h3>

<table class="table">
<?php foreach ($restaurants as $restaurant) : ?>
<tr>
    <td><a href=""><?php echo $this->escapeHtml($restaurant->name);?></a></td>
    <td><?php echo $this->escapeHtml($restaurant->address);?></td>
    <td><?php echo $this->escapeHtml($restaurant->phone);?></td>
    <td><div class="star" value="<?php echo $this->escapeHtml($restaurant->rank); ?>"></div></td>
</tr>
<?php endforeach; ?>
</table>

<script type="text/javascript">
		$(document).ready(function(){
                 $(".star").each(function(){
                    i=$(this).attr("value");
                    $(this).studyplay_star({MaxStar:12,CurrentStar:i,Enabled:false,Half:1});
		});    
                });
		
</script>